function detectionParams = getDefaultDetectionParams(params)
detectionParams = struct( ...
  'selectTopN', false, ...
  'useDecisionThresh', true, ...
  'overlap', params.overlapThreshold, ...
  'fixedDecisionThresh', -1);

%'overlap', 1.1, ...
%'overlap', params.overlapThreshold, ...
end
